### ISSUE TITLE
Plugin Initialize Error on CORE 1.20f

### ISSUE THREAD

**Issue by MuTong233** [RoxCian/TheAsphyxiaOfEternity#2]
[rb] error: failed to load
  [core] error: Unexpected token '.'
K:\LocalServer\AsphyxiaCORE\plugins\rb\handlers\rb1\common.ts:96
            await db_manager_1.DBM.overall(rid, base?.userId, "rb.rb1", "delete");
                                                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Module._compile (pkg/prelude/bootstrap.js:1281:32)
    at Module._compile (C:\snapshot\build-env\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object..ts (C:\snapshot\build-env\node_modules\ts-node\src\index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)

**Comment by RoxCian** [comment]
As #1 mentioned, you can remove "target": "esnext" in plugins/tsconfig.json, or just use CORE v1.30d since it targets to ES2017 (remember to back up your 1.20f save data first).

**Comment by MuTong233** [comment]
Simply update to 1.30d is impossible to solve this problem. Must remove that line from tsconfig.json
